version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/mongo:4.4.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: MongoDB Install 
          command: |
            apt-get install -y mongodb-org
      - run: mongod --version
      - run: mongod --port $DB_PORT &
  install:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: node-cache
          paths:
            - node_modules/
            - client/node_modules
  lint: 
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run lint 
  tsc: 
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys: 
            - node-cache
      - run: npm run tsc 
  unit-test:
    docker:
      - image: circleci/mongo:4.4.0
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: MongoDB Install 
          command: |
            apt-get install -y mongodb-org
      - run: mongod --version
      - run: mongod --port $DB_PORT &
      - run: npm install
      - run: npm run start:server & npm run test
workflows:
  test:
    jobs:
      - install
      - lint:
          requires:
          - install
      - tsc:
          requires:
          - install
      - unit-test:
          requires:
          - install