version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm install eslint-config-react-app
      - run: npm install eslint-plugin-testing-library@latest --save-dev
      - run: npm run lint
workflows:
  lint:
    jobs:
      - lint