version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  lint: 
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run lint 
  tsc: 
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run tsc
workflows:
  test:
    jobs:
      - lint
      - unit-test