version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/mongo:4.4.0
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt-get install -y mongodb
  lint: 
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run lint 
  tsc: 
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run tsc 
  unit-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run start:server & npm run test
workflows:
  test:
    jobs:
      - build
      - lint:
          requires: 
          - build
      - tsc:
          requires: 
          - build
      - unit-test:
          requires: 
          - build