version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  install:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm run lint
workflows:
  lint:
    jobs:
      - install
      - lint


